<?php
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/

$dictionary['av_Task_Template'] = array(
	'table'=>'av_task_template',
	'audited'=>true,
	'duplicate_merge'=>true,
	'fields'=>array (
	  'subject' => 
	  array (
		'required' => false,
		'name' => 'subject',
		'vname' => 'LBL_SUBJECT',
		'type' => 'varchar',
		'massupdate' => 0,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
	  ),
	  'private' => 
	  array (
		'required' => false,
		'name' => 'private',
		'vname' => 'LBL_PRIVATE',
		'type' => 'bool',
		'massupdate' => 0,
		'default' => '0',
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
	  ),
	  'task_category' => 
	  array (
		'required' => false,
		'name' => 'task_category',
		'vname' => 'LBL_TASK_CATEGORY',
		'type' => 'enum',
		'massupdate' => 0,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => 100,
		'size' => '20',
		'options' => 'task_category_list',
		'studio' => 'visible',
		'dependency' => false,
	  ),
	  'priority' => 
	  array (
		'required' => false,
		'name' => 'priority',
		'vname' => 'LBL_PRIORITY',
		'type' => 'enum',
		'massupdate' => 0,
		'default' => 'High',
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => 100,
		'size' => '20',
		'options' => 'task_priority_dom',
		'studio' => 'visible',
		'dependency' => false,
	  ),
	  'notify_child_completion' => 
	  array (
		'required' => false,
		'name' => 'notify_child_completion',
		'vname' => 'LBL_NOTIFY_CHILD_COMPLETION',
		'type' => 'bool',
		'massupdate' => 0,
		'default' => '0',
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
	  ),
	  'on_task_list' => 
	  array (
		'required' => false,
		'name' => 'on_task_list',
		'vname' => 'LBL_ON_TASK_LIST',
		'type' => 'bool',
		'massupdate' => 0,
		'default' => '0',
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
	  ),
	  'client_task' => 
	  array (
		'required' => false,
		'name' => 'client_task',
		'vname' => 'LBL_CLIENT_TASK',
		'type' => 'bool',
		'massupdate' => 0,
		'default' => '0',
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
	  ),
	  'assign_to' => 
	  array (
		'required' => false,
		'name' => 'assign_to',
		'vname' => 'LBL_ASSIGN_TO',
		'type' => 'enum',
		'massupdate' => 0,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => 100,
		'size' => '20',
		'options' => 'task_assign_to_list',
		'studio' => 'visible',
		'dependency' => false,
		'default' => 'Current_User',
	  ),
	  
	  'relate_to' => 
	  array (
		'required' => false,
		'name' => 'relate_to',
		'vname' => 'LBL_RELATE_TO',
		'type' => 'enum',
		'massupdate' => 0,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => 100,
		'size' => '20',
		'options' => 'task_relate_to_list',
		'studio' => 'visible',
		'dependency' => false,
		'default' => 'Related_To',
	  ),
	  'days_out' => 
	  array (
		'required' => false,
		'name' => 'days_out',
		'vname' => 'LBL_DAYS_OUT',
		'type' => 'int',
		'massupdate' => 0,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'calculated' => false,
		'len' => '255',
		'size' => '20',
		'enable_range_search' => false,
		'disable_num_format' => '',
	  ),
	  'parent_tasks_template' => array (
		'name' => 'parent_tasks_template',
		'type' => 'link',
		'relationship' => 'parent_tasks_template',
		'module' => 'av_Task_Template',
		'bean_name' => 'av_Task_Template',
		'source' => 'non-db',
		'vname' => 'LBL_PARENT_TASKS',
	  ),
	  'dependent_on' =>array (
		'name' => 'dependent_on',
		'type' => 'link',
		'relationship' => 'parent_tasks_template',
		'module' => 'av_Task_Template',
		'bean_name' => 'av_Task_Template',
		'link_type' => 'one',
		'source' => 'non-db',
		'vname' => 'LBL_PARENT_TASKS',
		'side' => 'right',
	  ),
	  'parent_tasks_name' =>array (
		'name' => 'parent_tasks_name',
		'rname' => 'name',
		'id_name' => 'parent_tasks_id',
		'vname' => 'LBL_PARENT_TASKS',
		'type' => 'relate',
		'isnull' => 'true',
		'table' => 'av_Task_Template',
		'module' => 'av_Task_Template',
		'massupdate' => false,
		'source' => 'non-db',
		'len' => 36,
		'link' => 'dependent_on',
		'unified_search' => true,
		'importable' => 'true',
	  ),
	  'parent_tasks_id' =>array (
		'name' => 'parent_tasks_id',
		'vname' => 'LBL_PARENT_TASKS_ID',
		'type' => 'id',
		'required' => false,
		'reportable' => false,
		'audited' => true,
	  ),
	  'av_Workflow' =>array (
		'name' => 'av_Workflow',
		'type' => 'link',
		'relationship' => 'av_Workflow',
		'module' => 'av_Workflow',
		'bean_name' => 'av_Workflow',
		'link_type' => 'one',
		'source' => 'non-db',
		'vname' => 'LBL_RT_WORKFLOW',
		'side' => 'right',
	  ),
	  'av_Workflow_name' =>array (
		'name' => 'av_Workflow_name',
		'rname' => 'name',
		'id_name' => 'av_Workflow_id',
		'vname' => 'LBL_RT_WORKFLOW_NAME',
		'type' => 'relate',
		'isnull' => 'true',
		'table' => 'av_Workflow',
		'module' => 'av_Workflow',
		'massupdate' => false,
		'source' => 'non-db',
		'len' => 36,
		'link' => 'av_Workflow',
		'unified_search' => true,
		'importable' => 'true',
	  ),
	  'av_Workflow_id' =>array (
		'name' => 'av_Workflow_id',
		'vname' => 'LBL_RT_WORKFLOW_ID',
		'type' => 'id',
		'required' => false,
		'reportable' => false,
		'audited' => true,
	  ),
	  'tree' => 
	  array (
		'name' => 'tree',
		'vname' => 'LBL_TREE',
		'type' => 'text',
		'source' => 'non-db'
	  ),
	),
	'relationships'=>array (
		'parent_tasks_template' => 
		array (
		  'lhs_module' => 'av_Task_Template',
		  'lhs_table' => 'av_task_template',
		  'lhs_key' => 'id',
		  'rhs_module' => 'av_Task_Template',
		  'rhs_table' => 'av_task_template',
		  'rhs_key' => 'parent_tasks_id',
		  'relationship_type' => 'one-to-many',
		),
		'av_workflow_av_task_template' => 
		array (
		  'lhs_module' => 'av_Workflow',
		  'lhs_table' => 'av_Workflow',
		  'lhs_key' => 'id',
		  'rhs_module' => 'av_Task_Template',
		  'rhs_table' => 'av_task_template',
		  'rhs_key' => 'av_Workflow_id',
		  'relationship_type' => 'one-to-many',
		),
	),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('av_Task_Template','av_Task_Template', array('basic','team_security','assignable'));
