<?php
 // created: 2013-04-12 20:54:23
$dictionary['av_Tax_Returns']['fields']['tax_year']['name']='tax_year';
$dictionary['av_Tax_Returns']['fields']['tax_year']['vname']='LBL_TAX_YEAR';
$dictionary['av_Tax_Returns']['fields']['tax_year']['type']='int';
$dictionary['av_Tax_Returns']['fields']['tax_year']['len']='11';
$dictionary['av_Tax_Returns']['fields']['tax_year']['audited']=0;
$dictionary['av_Tax_Returns']['fields']['tax_year']['required']=0;
$dictionary['av_Tax_Returns']['fields']['tax_year']['comment']='';
$dictionary['av_Tax_Returns']['fields']['tax_year']['default']='';
$dictionary['av_Tax_Returns']['fields']['tax_year']['massupdate']=0;
$dictionary['av_Tax_Returns']['fields']['tax_year']['reportable']=true;
$dictionary['av_Tax_Returns']['fields']['tax_year']['importable']=true;
$dictionary['av_Tax_Returns']['fields']['tax_year']['duplicate_merge']='enabled';
$dictionary['av_Tax_Returns']['fields']['tax_year']['duplicate_merge_dom_value']=true;
$dictionary['av_Tax_Returns']['fields']['tax_year']['help']='';
$dictionary['av_Tax_Returns']['fields']['tax_year']['group']='';
$dictionary['av_Tax_Returns']['fields']['tax_year']['merge_filter']='disabled';
$dictionary['av_Tax_Returns']['fields']['tax_year']['calculated']=false;
$dictionary['av_Tax_Returns']['fields']['tax_year']['enable_range_search']=false;
$dictionary['av_Tax_Returns']['fields']['tax_year']['disable_num_format']=true;
 ?>