<?php
 // created: 2013-03-28 01:01:24
$dictionary['av_Cashflow']['fields']['year']['name']='year';
$dictionary['av_Cashflow']['fields']['year']['vname']='LBL_YEAR';
$dictionary['av_Cashflow']['fields']['year']['type']='int';
$dictionary['av_Cashflow']['fields']['year']['len']='11';
$dictionary['av_Cashflow']['fields']['year']['audited']=0;
$dictionary['av_Cashflow']['fields']['year']['required']=0;
$dictionary['av_Cashflow']['fields']['year']['comment']='';
$dictionary['av_Cashflow']['fields']['year']['default']='';
$dictionary['av_Cashflow']['fields']['year']['massupdate']=0;
$dictionary['av_Cashflow']['fields']['year']['reportable']=true;
$dictionary['av_Cashflow']['fields']['year']['importable']=true;
$dictionary['av_Cashflow']['fields']['year']['duplicate_merge']='enabled';
$dictionary['av_Cashflow']['fields']['year']['duplicate_merge_dom_value']=true;
$dictionary['av_Cashflow']['fields']['year']['help']='';
$dictionary['av_Cashflow']['fields']['year']['group']='';
$dictionary['av_Cashflow']['fields']['year']['merge_filter']='disabled';
$dictionary['av_Cashflow']['fields']['year']['calculated']=false;
$dictionary['av_Cashflow']['fields']['year']['enable_range_search']=false;
$dictionary['av_Cashflow']['fields']['year']['disable_num_format']=true;
 ?>