<?php
$dictionary['Task']['fields']['category'] = array(
  'required' => false,
  'name' => 'category',
  'vname' => 'LBL_CATEGORY',
  'type' => 'enum',
  'massupdate' => '0',
  'default' => '',
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'reportable' => true,
  'len' => 100,
  'size' => '20',
  'options' => 'task_category_list',
  'studio' => 'visible',
  'dbType' => 'enum',
);