<?php
$dictionary["Account"]["fields"]["current_net_worth"] = array (
  'required' => false,
  'name' => 'current_net_worth',
  'vname' => 'LBL_CURRENT_NET_WORTH',
  'type' => 'function',
  'massupdate' => 0,
  'comments' => '',
  'help' => '',
  'importable' => 'false',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'reportable' => true,
  'len' => 26,
  'size' => '20',
  'source' => 'function',
  'function_name' => 'getCurrentNetWorth',
  'function_params' => array('id'),
  'function_params_source' => 'this',
  'function_require' => 'custom/modules/Accounts/calc_worth_and_managed_assets.php',
  'enforced' => true,
  'dependency' => '',
  'enable_range_search' => false,
);